"""Ingredients and recipes

Revision ID: 31f001e69e95
Revises: 
Create Date: 2021-06-18 21:24:03.661030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f001e69e95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aisle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ingredients_recipes',
    sa.Column('recipe', sa.String(), nullable=True),
    sa.Column('ingredient', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True)
    )
    op.create_table('recipes',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('ingredients_recipes')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
