"""Unique in the join table

Revision ID: 758f56042a14
Revises: 8fc983ca80f2
Create Date: 2022-03-09 00:38:18.131593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758f56042a14'
down_revision = '8fc983ca80f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('recipe_ingredient_key', 'ingredients_recipes', ['recipe', 'ingredient'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_ingredient_key', 'ingredients_recipes', type_='unique')
    # ### end Alembic commands ###
