"""Adding 'stocked' column

Revision ID: 8fc983ca80f2
Revises: 31f001e69e95
Create Date: 2022-03-06 15:29:18.505658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc983ca80f2'
down_revision = '31f001e69e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('stocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'stocked')
    # ### end Alembic commands ###
